### ISSUE TITLE
sorting order of m_bids and m_asks

### ISSUE THREAD

**Issue by ferencdg** [charles-cooper/itch-order-book#11]
sorry, if I misread the code, but

shouldn't be the m_bids sorted ascending and the m_offers sorted decreasing based on the price? Because currently it seems both are sorted ascending. So when you add a new offer, you try to search for the place in the m_offers array from the wrong side. (by wrong, I mean it is more likely that the new order will be added around the current market price)

**Comment by charles-cooper** [comment]
it's a good question! but there is no mistake. this routine converts the sign bit on the price depending on if the order is a buy or sell:
https://github.com/charles-cooper/itch-order-book/blob/095ac97ef46c72411a62dd9148d96d2e3ace3305/main.cpp#L26-L32

so sell orders are represented as having negative prices. this produces an efficiency because you don't need to branch when comparing prices or use a function pointer or anything, you can just use `>` (which just compiles to a single instruction on x86 - and i'm assuming pretty much all real architectures for that matter) as here :
https://github.com/charles-cooper/itch-order-book/blob/095ac97ef46c72411a62dd9148d96d2e3ace3305/order_book.h#L240-L243

so i guess when thinking about prices, it's helpful to think about `>` as being "better than" instead of "greater than". hope this helps!
