### ISSUE TITLE
[Question] Clarification on the Role of execute_order in Relation to add_order

### ISSUE THREAD

**Issue by sgiulians** [charles-cooper/itch-order-book#13]
I apologize if this question seems basic, but I'm trying to understand the architectural decision behind the execute_order method in your order book implementation. From my understanding, typically in an order-driven market, trades occur automatically when a new order crosses the bid-ask spread. Given this, I'm curious why execute_order is implemented as a separate method that requires external invocation. Shouldn't the add_order function be designed to automatically trigger a trade execution if the new order's price crosses the spread? Could you please explain the rationale behind requiring execute_order to be called separately instead of handling this within the add_order logic?

Thank you for your time and help!

**Comment by brettf1200** [comment]
I can answer this. It's implemented that way because that's how the ITCH protocol specification says it should be implemented. Internally, the matching engine at the exchange does more or less what you describe and then emits a series of events in the ITCH protocol format that need to be applied to your local copy of the orderbook to keep it in sync with the exchange's copy of the order book inside the matching engine. This code isn't a matching engine - it's an implementation of a protocol that is designed to keep your local copy of the order book in sync with the matching engine's copy in an efficient way.

**Comment by sgiulians** [comment]
Thank you for the thorough explanation; now everything is very clear!
