### ISSUE TITLE
Ask levels in reverse order?

### ISSUE THREAD

**Issue by enricodetoma** [charles-cooper/itch-order-book#7]
This is more a question than an issue: why don't you keep the ask levels in reverse sorted order?

Since most updates appear near best bid/ask, keeping ask levels in reverse sorted order would mean to have best ask at the end of the vector instead of at the beginning, thus being more efficient, if I'm not mistaken.

**Comment by charles-cooper** [comment]
> This is more a question than an issue: why don't you keep the ask levels in reverse sorted order?
> 
> Since most updates appear near best bid/ask, keeping ask levels in reverse sorted order would mean to have best ask at the end of the vector instead of at the beginning, thus being more efficient, if I'm not mistaken.

Hey @enricodetoma great question. I actually had a bit of a double take because I wrote this code several years ago and I assume I would have done something like that. And at first glance it looks like I didn't. But actually I did.

It's a bit hidden but if you squint closely the price also encodes whether the order is a buy or sell (https://github.com/charles-cooper/itch-order-book/blob/1e0ce103083a7c3a8ed4da5c6ffd3fe690b84849/order_book.h#L64)

In case you missed it, the sign is set outside of the call to add_order: https://github.com/charles-cooper/itch-order-book/blob/1e0ce103083a7c3a8ed4da5c6ffd3fe690b84849/main.cpp#L86

This is legal because the spec limits prices to a number smaller than `2^31`.
> The maximum value of price (4) in TotalView--­ITCH is 200,000.0000 (decimal, 77359400 hex).

I also check it here: https://github.com/charles-cooper/itch-order-book/blob/1e0ce103083a7c3a8ed4da5c6ffd3fe690b84849/main.cpp#L28 So we can use that high bit for the buy/sell flag.

Once you have that, the ask levels actually do get mapped to "reverse" logical order, because the sign bit also conveniently reverses the comparison in https://github.com/charles-cooper/itch-order-book/blob/1e0ce103083a7c3a8ed4da5c6ffd3fe690b84849/order_book.h#L240, maintaining a reverse sorted invariant in the ask levels. I figured this was more efficient than using templates or function pointers because templates introduce code bloat, and function pointers introduce indirection; meanwhile signed comparison maps to a single instruction on x86.

Hope this answers your question. If so please close the issue!

**Comment by enricodetoma** [comment]
Thank you very much for the clear explanation! 
I completely missed the fact that you set negative sign for ask orders.
